# Generated by Django 5.2.6 on 2025-09-12 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('update', 'Update'), ('regional', 'Regional'), ('global', 'Global'), ('antique', 'Antique'), ('special', 'Special')], default='global', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
