# Generated by Django 5.2.6 on 2025-09-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car'),
        ('main', '0003_products_user'),
    ]

    operations = [
    ]
