# Generated by Django 5.2.6 on 2025-09-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_0003_car_0003_products_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
